spring:
  application:
    name: logging-monitoring-service

server:
  port: 8086

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

info:
  app:
    name: ${spring.application.name}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    root: INFO
    com.yourcompany.loggingservice: DEBUG

zipkin:
  base-url: http://localhost:9411

app:
  config:
    kafka:
      bootstrap-servers: localhost:9092
      topic: log-events